using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ordering.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// The denormalized projection tables. They are written only by the outbox
    /// projector (and the catalog seeder) and read only via Dapper — EF Core
    /// never maps them, which is why this migration is raw SQL.
    /// </summary>
    public partial class ReadModel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE read_restaurants (
                    id uuid PRIMARY KEY,
                    name text NOT NULL,
                    city text NOT NULL
                );

                CREATE TABLE read_menus (
                    restaurant_id uuid PRIMARY KEY,
                    menu jsonb NOT NULL
                );

                CREATE TABLE read_orders (
                    order_id uuid PRIMARY KEY,
                    restaurant_id uuid NOT NULL,
                    customer_id text NOT NULL,
                    status text NOT NULL,
                    total bigint NOT NULL,
                    lines jsonb NOT NULL,
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL,
                    expires_at timestamptz NOT NULL,
                    refund_attempts int NOT NULL DEFAULT 0,
                    last_refund_error text NULL,
                    manual_intervention boolean NOT NULL DEFAULT false
                );

                CREATE INDEX ix_read_orders_restaurant_status ON read_orders (restaurant_id, status, created_at);

                CREATE TABLE read_order_history (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id uuid NOT NULL,
                    from_status text NULL,
                    to_status text NOT NULL,
                    actor text NOT NULL,
                    at timestamptz NOT NULL,
                    reason text NULL
                );

                CREATE INDEX ix_read_order_history_order ON read_order_history (order_id, id);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS read_order_history;
                DROP TABLE IF EXISTS read_orders;
                DROP TABLE IF EXISTS read_menus;
                DROP TABLE IF EXISTS read_restaurants;
                """);
        }
    }
}
