// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ordering.Infrastructure.Persistence;

#nullable disable

namespace Ordering.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260824071836_InitialWriteModel")]
    partial class InitialWriteModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ordering.Domain.Catalog.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BasePrice")
                        .HasColumnType("bigint")
                        .HasColumnName("base_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_menu_items");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_menu_items_restaurant_id");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.Modifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ModifierGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("modifier_group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("PriceDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("price_delta");

                    b.HasKey("Id")
                        .HasName("pk_modifiers");

                    b.HasIndex("ModifierGroupId")
                        .HasDatabaseName("ix_modifiers_modifier_group_id");

                    b.ToTable("modifiers", (string)null);
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.ModifierGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MaxSelect")
                        .HasColumnType("integer")
                        .HasColumnName("max_select");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("MinSelect")
                        .HasColumnType("integer")
                        .HasColumnName("min_select");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_modifier_groups");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_modifier_groups_menu_item_id");

                    b.ToTable("modifier_groups", (string)null);
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_restaurants_city");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("Ordering.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChargeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("charge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastRefundError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_refund_error");

                    b.Property<string>("Lines")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lines");

                    b.Property<bool>("ManualInterventionRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("manual_intervention_required");

                    b.Property<DateTimeOffset?>("NextRefundAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_refund_attempt_at");

                    b.Property<int>("RefundAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("refund_attempts");

                    b.Property<string>("RefundId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("refund_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("Total")
                        .HasColumnType("bigint")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ChargeId")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_charge_id");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .HasDatabaseName("ix_orders_customer_id_created_at");

                    b.HasIndex("CustomerId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_customer_idempotency_key");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_orders_status_expires_at");

                    b.HasIndex("Status", "NextRefundAttemptAt")
                        .HasDatabaseName("ix_orders_status_next_refund_attempt_at");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_orders_status_updated_at");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Ordering.Domain.Orders.StatusHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("From")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_status_history");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_status_history_order_id");

                    b.ToTable("status_history", (string)null);
                });

            modelBuilder.Entity("Ordering.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.MenuItem", b =>
                {
                    b.HasOne("Ordering.Domain.Catalog.Restaurant", null)
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_restaurants_restaurant_id");
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.Modifier", b =>
                {
                    b.HasOne("Ordering.Domain.Catalog.ModifierGroup", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("ModifierGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modifiers_modifier_groups_modifier_group_id");
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.ModifierGroup", b =>
                {
                    b.HasOne("Ordering.Domain.Catalog.MenuItem", null)
                        .WithMany("ModifierGroups")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modifier_groups_menu_items_menu_item_id");
                });

            modelBuilder.Entity("Ordering.Domain.Orders.StatusHistoryEntry", b =>
                {
                    b.HasOne("Ordering.Domain.Orders.Order", null)
                        .WithMany("History")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_history_orders_order_id");
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.MenuItem", b =>
                {
                    b.Navigation("ModifierGroups");
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.ModifierGroup", b =>
                {
                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("Ordering.Domain.Catalog.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Ordering.Domain.Orders.Order", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
